task:
  id: 1
  title: Absolute value
  text: Return absolute value of a real number
  processor: python3.6

tests:
  - input: 0.0
    output: 0.0
    comparator:
      name: exact
  - input: 1.5
    output: 1.5
    comparator:
      name: exact
  - input: -1.5
    output: 1.5
    comparator:
      name: exact
